version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-2"
    AWS_ACCOUNT_ID: "585008087112"
    ECR_REPOSITORY_NAME: "nhanntnta/code-demo"
    AWS_ECS_CLUSTER: "nhannt-ecs-demo"
    AWS_ECS_SERVICE: "svc-demo"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies with yum..."
      - yum update -y
      - yum install -y jq curl unzip aws-cli
      - aws --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Setting up variables..."
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - echo "Repository URI is $REPOSITORY_URI"
      - IMAGE_TAG=$(git rev-parse --short HEAD || echo "latest")
      - echo "Image tag is $IMAGE_TAG"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo "Tagging the Docker image..."
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"simple-app","imageUri":"%s"}]'
        $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json